name: test-and-lint
on:
  pull_request:
  push:
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.52.2
          working-directory: '.'
          skip-go-installation: true
      - name: Test
        run: 'go test -timeout=5m -race -v ./...'
